### ISSUE TITLE
playbooks unified vs not unified

### ISSUE THREAD

**Issue by adonisgarciac** [automationiberia/controller-casc-cd#6]
Are both playbooks necessary? unified and normal? If not, we should remove one of them.

**Comment by adonisgarciac** [comment]
https://gitlab.com/automationiberia/aap-cac/superadmin-workshop-template/-/merge_requests/1

**Comment by ivarmu** [comment]
Yes, they are both needed... the Unified ones are for the managed organizations, meanwhile the non-unified ones are for the superadmin one. They work in a different way, as the unified playbook is git-clonning the managed organization's repository, and that's not needed by the superadmin organization. 

Anyway, we can modify it and use the unified playbooks everywhere... opinions?

**Comment by adonisgarciac** [comment]
+1 to have only a single playbook :-D

IMHO, the controller and the CasC will be more clean to manage. But we need more opinions, we can discuss about this and the rest of issues on Friday.
