### ISSUE TITLE
Only indicate manual or automatically

### ISSUE THREAD

**Issue by adonisgarciac** [automationiberia/controller-casc-cd#7]
I think that to have both possibilities will bring problems to the user. Even me, I had problems to understand how to do it.

In the automatically form, It's difficult to understand for the user what we have to set for gitlab_action_tag or for Trigger hook on push events? .

**Comment by ivarmu** [comment]
write with tabs for both options

**Comment by ivarmu** [comment]
https://github.com/automationiberia/controller-casc-cd/pull/15 has collapsed the both methods using tabs.
